import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import dynamic from "next/dynamic";

const Editor = dynamic(
  () =>
    import("monaco-editor").then((mod) => {
      const editor = mod.default.editor.create(
        document.querySelector(".container")!,
        {
          value: ``,
          language: "json",
        }
      );

      return <div>hey</div>;
    }),
  {
    ssr: false,
  }
);

export default function Home() {
  const [postBody, setPostBody] = useState(`{
    "userId": 1,
    "id": 1,
    "title": "delectus aut autem",
    "completed": false
  }`);

  useEffect(() => {
    // console.log(window.MonacoEnvironment);
    if (typeof navigator !== "undefined") {
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-blue-400">textsdf safd s fda</div>
      <div className="container"></div>
    </>
  );
}
