import { CSRWrapper } from './CSRWrapper'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const data = {
    name: "jun",
    age: "18"
  }
  return (
    <html lang="en">
      <body>
        <CSRWrapper data={data}>
          {children}
        </CSRWrapper>
      </body>
    </html>
  )
}
